sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before-install:
  - npm install -g bower grunt-cli karma
install:
  - npm install
  - bower install
before-script:
  - grunt build
