sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before-install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before-script:
  - npm install -g bower grunt-cli karma
  - npm install
  - bower install
  - grunt build
script: grunt