sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli bower karma grunt-karma
before_script:
  - bower install
  - grunt build
script: grunt test-travis
