sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before-script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g karma
  - npm install -g grunt-karma
  - npm install
  - bower install
  - grunt build
